[package]
name = "bulk"
version = "0.1.0"
edition = "2018"

[dependencies]
libc = "*"
rand = "*"
hex = "*"
regex = "*"
log = "*"
env_logger = "*"
lazy_static = "*"
fallible-iterator = "*"
sha2 = "*"
thiserror = "*"
anyhow = "*"
clap = "*"
git2 = "*"
fuser = "*"
termcolor = "*"
