#!/usr/bin/env bash

set -Eeuo pipefail

subject="$1"
out="$2"

test ! -d "$out"

source="$out/source"
nodes="$out/nodes"
files="$out/files"
digests="$out/digests"

mkdir -p "$out"
printf "%s" "$subject" > "$source"
find "$subject" -fprintf "$nodes" '%y %#m %P\0%l\0'
find "$subject" -type f -fprintf "$files" '%P\0'

(
    cd "$subject"
    while IFS= read -r -d $'\0' path; do
        sha256sum -bz "$path"
    done
) < "$files" > "$digests"
